# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-06-29 04:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislikepostreactions',
            name='bios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DisLikePostReactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
