# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-06-29 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20210629_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepost',
            name='bio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='LikePost', to='User.Bio'),
            preserve_default=False,
        ),
    ]
