# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-06-29 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20210629_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepost',
            name='bio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LikePost', to='User.Bio'),
        ),
    ]
