# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-06-30 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_auto_20210629_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislikepostreactions',
            name='bios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DisLikePostReactions', to='User.Bio'),
        ),
    ]
