# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-04-30 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='photo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
