# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-13 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTPs',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.BaseModel')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
            ],
            bases=('User.basemodel',),
        ),
    ]
