# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-15 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_emailotps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='dislike',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='like',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='me',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
