# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-15 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20210715_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='occupant_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
