# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-23 18:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_customuser_occupant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherSettings',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.BaseModel')),
                ('direct_message', models.BooleanField(default=False)),
                ('chat_alert', models.BooleanField(default=False)),
                ('allow_mentions', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('User.basemodel',),
        ),
        migrations.CreateModel(
            name='PostNotification',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.BaseModel')),
                ('comments', models.BooleanField(default=False)),
                ('like_dislike', models.BooleanField(default=False)),
                ('every_hour', models.BooleanField(default=False)),
                ('every_three_hours', models.BooleanField(default=False)),
                ('every_five_hours', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('User.basemodel',),
        ),
    ]
