# Generated by Django 3.2.4 on 2021-06-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='cover_photo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
