# Generated by Django 3.2.4 on 2021-06-15 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_bio_cover_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='blocked_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_user', to='User.customuser'),
            preserve_default=False,
        ),
    ]
