# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-01 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20210701_2220'),
        ('Post', '0003_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisLikePostReactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField()),
                ('favorite', models.IntegerField()),
                ('dislike', models.IntegerField()),
                ('share', models.IntegerField()),
                ('seen', models.IntegerField()),
                ('comment', models.TextField(null=True)),
                ('bios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DisLikePostReactions', to='User.Bio')),
            ],
        ),
        migrations.CreateModel(
            name='LikePostReactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField()),
                ('favorite', models.IntegerField()),
                ('dislike', models.IntegerField()),
                ('share', models.IntegerField()),
                ('seen', models.IntegerField()),
                ('comment', models.TextField(null=True)),
                ('bios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LikePostReactions', to='User.Bio')),
            ],
        ),
        migrations.RemoveField(
            model_name='reactions',
            name='dislike_post',
        ),
        migrations.RemoveField(
            model_name='reactions',
            name='like_post',
        ),
        migrations.RemoveField(
            model_name='reactions',
            name='users',
        ),
        migrations.RemoveField(
            model_name='dislikepost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='user',
        ),
        migrations.AddField(
            model_name='dislikepost',
            name='bio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DislikePost', to='User.Bio'),
        ),
        migrations.AddField(
            model_name='dislikepost',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='likepost',
            name='bio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LikePost', to='User.Bio'),
        ),
        migrations.AddField(
            model_name='likepost',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Reactions',
        ),
        migrations.AddField(
            model_name='likepostreactions',
            name='like_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LikePostReactions', to='Post.LikePost'),
        ),
        migrations.AddField(
            model_name='dislikepostreactions',
            name='dislike_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DisLikePostReactions', to='Post.DislikePost'),
        ),
    ]
